name: Sway Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  check:
    name: Sway project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Fuel toolchain
        uses: FuelLabs/action-fuel-toolchain@v0.6.0
        with:
          toolchain: beta-3

      - name: Build Hello World Contract 1
        run: forc build --path ./sway/1-hello-world

      - name: Build Counter Contract 2
        run: forc build --path ./sway/2-counter

      - name: Build Logging Contract 3
        run: forc build --path ./sway/3-logging

      - name: Build Storage Contract 4
        run: forc build --path ./sway/4-storage

      - name: Build Conditional Contract 5
        run: forc build --path ./sway/5-conditional

      - name: Build Structs Contract 6
        run: forc build --path ./sway/6-structs

      - name: Build Errors Contract 7
        run: forc build --path ./sway/7-errors

      - name: Build Functions Contract 8
        run: forc build --path ./sway/8-functions

      - name: Build Functions Contract 9
        run: forc build --path ./sway/9-amounts

      - name: Build Functions Contract 10
        run: forc build --path ./sway/10-message-info

      - name: Build Functions Contract 11
        run: forc build --path ./sway/11-gas-info

      - name: Build Functions Contract 12
        run: forc build --path ./sway/12-contract-info

      - name: Build Functions Contract 13
        run: forc build --path ./sway/13-block-info

      - name: Build Functions Contract 14
        run: forc build --path ./sway/14-transfer

      - name: Build Functions Contract 15
        run: forc build --path ./sway/15-mint-tokens

      - name: Build Functions Contract 16
        run: forc build --path ./sway/16-hashing

      - name: Build Functions Contract 17
        run: forc build --path ./sway/17-ec-recover

      - name: Build Functions Contract 18
        run: forc build --path ./sway/18-re-entrancy

      - name: Build Functions Contract 19
        run: forc build --path ./sway/19-unsigned-ints

      - name: Build Functions Contract 20
        run: forc build --path ./sway/20-contract-calls
